CityTour.WebApp/Controllers/GuestController.cs
using AutoMapper;
using CityTour.Domain;
using CityTour.Domain.Services;
using CityTour.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CityTour.WebApp.Controllers
{
    public class GuestController : Controller
    {        
        private readonly IGuestService guestService;
        private readonly IGuestItineararyRequestService requestService;
        private readonly IItineararyService itinerarryService;

        private readonly IMapper mapper;

        private const string tempDataGuestsKey = nameof(GuestItineraryRequestViewModel.Guests);
        private const string tempDataPointsKey = nameof(GuestItineraryRequestViewModel.ItineraryPoints);
        
        public GuestController(
              IGuestService guestService
            , IGuestItineararyRequestService requestService
            , IItineararyService itineraryService
            , IMapper mapper)
        {
            if (guestService == null)
            {
                throw new ArgumentNullException(nameof(guestService));
            }

            if (requestService == null)
            {
                throw new ArgumentNullException(nameof(requestService));
            }

            if (itineraryService == null)
            {
                throw new ArgumentNullException(nameof(itineraryService));
            }

            if (mapper == null)
            {
                throw new ArgumentNullException(nameof(mapper));
            }

            this.guestService = guestService;
            this.requestService = requestService;
            this.itinerarryService = itineraryService;
            this.mapper = mapper;
        }
           
        // GET: Guest/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Guest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GuestViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                Guest guest = new Guest();
                mapper.Map(viewModel, guest);

                guestService.Save(guest);

               
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(viewModel);
            }
                       
        }

        // GET: Guest/CreateItineraryRequest
        public ActionResult CreateItineraryRequest()
        {            
            GuestItineraryRequestViewModel viewModel = new GuestItineraryRequestViewModel();
            Populate(viewModel, needsRefresh:true);

            return View(viewModel);
        }

        // POST: Guest/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateItineraryRequest(GuestItineraryRequestViewModel viewModel)
        {
            try
            {
                Guest guest = guestService.GetById(int.Parse(viewModel?.GuestId));
                GuestItineraryPoint endPoint = itinerarryService.GetBydId(int.Parse(viewModel?.ItineraryPointId));

                if (endPoint?.Guests.Any(item => item.Id == guest.Id) == true)
                {
                    ModelState.AddModelError(nameof(GuestItineraryRequestViewModel.GuestId), "Este huésped ya ha solicitado viajar al punto de interés selecionado");                    
                }

                if (ModelState.IsValid)
                {                    
                    endPoint.Guests.Add(guest);

                    requestService.Save(new GuestItineraryRequest() { EndPoint = endPoint });
                    return RedirectToAction("Index", "Home");
                }
            }
            catch
            {

            }

            Populate(viewModel);
            return View(viewModel);
        }

        private void Populate(GuestItineraryRequestViewModel viewModel, bool needsRefresh = false)
        {
            if (viewModel == null)
            {
                throw new ArgumentNullException(nameof(viewModel));
            }


            if (needsRefresh)
            {
                if (TempData.ContainsKey(tempDataGuestsKey)) TempData.Remove(tempDataGuestsKey);
                if (TempData.ContainsKey(tempDataPointsKey)) TempData.Remove(tempDataPointsKey);
            }
            

            if (!TempData.ContainsKey(tempDataGuestsKey))
            {
                var items = guestService
                    .GetAll()
                    .Select(item => new SelectListItem { Value = item.Id.ToString(), Text = item.Name + " " + item.FirstName })
                    .ToList();

                TempData.Add(tempDataGuestsKey, items);
            }
                        
            
            if (!TempData.ContainsKey(tempDataPointsKey))
            {
                var items = itinerarryService
                    .GetRequestedPoints()
                    .Select(item => new SelectListItem { Value = item.Id.ToString(), Text = item.Name })
                    .ToList();

                TempData.Add(tempDataPointsKey, items);
            }
            

            viewModel.Guests = TempData.Peek(nameof(GuestItineraryRequestViewModel.Guests)) as IList<SelectListItem>;
            viewModel.ItineraryPoints = TempData.Peek(nameof(GuestItineraryRequestViewModel.ItineraryPoints)) as IList<SelectListItem>;
        }
    }
}

CityTour.WebApp/Controllers/ItineraryController.cs
using AutoMapper;
using CityTour.Domain;
using CityTour.Domain.Services;
using CityTour.WebApp.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CityTour.WebApp.Controllers
{
    public class ItineraryController : Controller
    {
        private readonly IItineararyService itinerarryService;
        private readonly IMapper mapper;

        private const string tempDataPointsKey = nameof(ShowSummaryViewModel.ItineraryPoints);

        public ItineraryController(
            IItineararyService itinerarryService,
            IMapper mapper)
        {
            if (itinerarryService == null)
            {
                throw new ArgumentNullException(nameof(itinerarryService));
            }

            if (mapper == null)
            {
                throw new ArgumentNullException(nameof(mapper));
            }

            this.itinerarryService = itinerarryService;
            this.mapper = mapper;
        }
       
        public ActionResult ShowSummary()
        {
            ShowSummaryViewModel viewModel = new ShowSummaryViewModel();
            Populate(viewModel, needsRefresh: true);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowSummary(ShowSummaryViewModel viewModel)
        {
            try
            {             
                if (ModelState.IsValid)
                {
                    GuestItineraryPoint startPoint = itinerarryService.GetBydId(1);
                    GuestItineraryPoint endPoint   = itinerarryService.GetBydId(int.Parse(viewModel.ItineraryPointId));

                    var summaryInfo = itinerarryService.ShowSummary(startPoint, endPoint);
                    summaryInfo?.ForEach(summaryInfoItem =>
                    {
                        SummaryPointInfoViewModel summaryPointViewmodel = new SummaryPointInfoViewModel();
                        mapper.Map(summaryInfoItem, summaryPointViewmodel);

                        viewModel.SummaryInfoResults.Add(summaryPointViewmodel);
                    });
                }
            }
            catch
            {
                
            }

            Populate(viewModel);
            return View(viewModel);
        }

        private void Populate(ShowSummaryViewModel viewModel, bool needsRefresh = false)
        {
            if (viewModel == null)
            {
                throw new ArgumentNullException(nameof(viewModel));
            }


            if (needsRefresh)
            {                
                if (TempData.ContainsKey(tempDataPointsKey)) TempData.Remove(tempDataPointsKey);
            }


            if (!TempData.ContainsKey(tempDataPointsKey))
            {
                var items = itinerarryService
                    .GetRequestedPoints() 
                    .Select(item => new SelectListItem { Value = item.Id.ToString(), Text = item.Name })
                    .ToList();

                TempData.Add(tempDataPointsKey, items);
            }

            
            viewModel.ItineraryPoints = TempData.Peek(nameof(GuestItineraryRequestViewModel.ItineraryPoints)) as IList<SelectListItem>;
        }
    }
}

CityTour.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="wrap">
        <header id="header">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <button id="primary-nav-button" type="button">Menu</button>
                        <a href="index.html">
                            <div class="logo">
                                <img src="@Url.Content("~/Content/images/logo.png")">
                            </div>
                        </a>
                        <nav id="primary-nav" class="dropdown cf">
                            <ul class="dropdown menu">
                                <li class='active'>@Html.ActionLink("Inicio", "Index", "Home")</li>
                                <li class='active'>@Html.ActionLink("Registro", "Create", "Guest")</li>
                                <li class='active'>@Html.ActionLink("Solicitar Itinerario", "CreateItineraryRequest", "Guest")</li>
                                <li class='active'>@Html.ActionLink("Consultar Itinerario", "ShowSummary", "Itinerary")</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </header>
    </div>
    <section class="banner" id="top">
        <div class="container">
            @RenderBody()
        </div>
    </section>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="about-veno">
                        <div class="logo">
                            <img src="@Url.Content("~/Content/images/footer_logo.png")">
                        </div>
                        <p>Mauris sit amet quam congue, pulvinar urna et, congue diam. Suspendisse eu lorem massa. Integer sit amet posuere tellus, id efficitur leo. In hac habitasse platea dictumst.</p>
                        <ul class="social-icons">
                            <li>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-rss"></i></a>
                                <a href="#"><i class="fa fa-dribbble"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="useful-links">
                        <div class="footer-heading">
                            <h4>Links De Ayuda</h4>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <ul>
                                    <li><a href="#"><i class="fa fa-stop"></i>FAQs</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Registro</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Login</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Mi perfil</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Como funciona</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Acerca de nosotros</a></li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li><a href="#"><i class="fa fa-stop"></i>Nuestro clientes</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Partners</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Blog</a></li>
                                    <li><a href="#"><i class="fa fa-stop"></i>Contactar</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="contact-info">
                        <div class="footer-heading">
                            <h4>Informacion de contacto</h4>
                        </div>
                        <p>Praesent iaculis gravida elementum. Proin fermentum neque facilisis semper pharetra. Sed vestibulum vehicula tincidunt.</p>
                        <ul>
                            <li><span>Telefono:</span><a href="#">010-050-0550</a></li>
                            <li><span>Email:</span><a href="#">hi@company.co</a></li>
                            <li><span>Direccion:</span><a href="#">company.co</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <div class="sub-footer">
        <p>Copyright &copy; 2020 Bates Hotel</p>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>